services:
  app:
    image: app-laravel
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    hostname: php.laravel.test
    expose:
      - 9000
    networks:
      - test-laravel
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis

  db:
    image: postgres:18.3-alpine
    container_name: laravel-db
    hostname: db.laravel.test
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - test-laravel
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}

  front_dev:
    image: laravel-pnpm
    hostname: vue.laravel.test
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./:/app
    networks:
      - test-laravel

  nginx:
    image: nginx:1.30.0-alpine
    container_name: laravel-nginx
    hostname: laravel.test
    expose:
      - 80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test-laravel
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel-redis
    hostname: redis.laravel.test
    networks:
      - test-laravel

volumes:
  db-data: null

networks:
  test-laravel: null